### ISSUE TITLE
If you leave the game then rejoin it will leave the old hat and make a new one.

### ISSUE THREAD

**Issue by GoGitBlarfart** [presssssure/team-create-hats#4]
![Screenshot 2020-11-28 090934](https://user-images.githubusercontent.com/67515294/100517594-9bc28900-3159-11eb-929f-7480cb924c82.png)
![Screenshot 2020-11-28 090949](https://user-images.githubusercontent.com/67515294/100517595-9bc28900-3159-11eb-88a5-f200e8bb52e2.png)

**Comment by presssssure** [comment]
This is intentional. Roblox doesn't provide a method to execute code when studio closes, so the best solution that I've found is to make the Archivable property false for the folder the hat is in. I'll look into having a solution similar to (if not the same as) #2 sometime in the future, which should help mitigate this problem.

**Comment by presssssure** [comment]
Fixed in version 4.0.0
